language: java
jdk:
  - oraclejdk8

sudo: false

addons:
  sonarcloud:
    organization: "thleu-github"

before_install:
  - chmod +x gradlew
after_success:
  - ./gradlew jacocoTestReport coveralls
  - ./gradlew sonarqube